-flattenpackagehierarchy com.aitime.android.payment
-keepnames class * implements com.aitime.android.payment.core.IPayment
-keep class com.google.android.** {*;}
-keep class com.gocashfree.cashfreesdk.** {*;}
